version: '2'
services:

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/data

  web:
    restart: always
    build: &build
      context: .
      dockerfile: Dockerfile-development
    image: mastodon-development
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes: &app
      - ./.rspec:/mastodon/.rspec
      - ./.rubocop.yml:/mastodon/.rubocop.yml
      - ./.ruby-version:/mastodon/.ruby-version
      - ./.yardopts:/mastodon/.yardopts
      - ./app:/mastodon/app
      - ./bin:/mastodon/bin
      - ./config:/mastodon/config
      - ./config.ru:/mastodon/config.ru
      - ./db:/mastodon/db
      - ./docs:/mastodon/docs
      - ./Gemfile:/mastodon/Gemfile
      - ./Gemfile.lock:/mastodon/Gemfile.lock
      - ./package.json:/mastodon/package.json
      - ./yarn.lock:/mastodon/yarn.lock
      - ./lib:/mastodon/lib
      - ./public:/mastodon/public
      - ./public/packs:/mastodon/public/packs
      - ./spec:/mastodon/spec
      - ./storybook:/mastodon/storybook
      - ./streaming:/mastodon/streaming
      - ./vendor/assets:/mastodon/vendor/assets
      - ./tmp/letter_opener:/mastodon/tmp/letter_opener

  webpack:
    restart: always
    build: *build
    image: mastodon-development
    env_file: .env
    command: /mastodon/bin/webpack-dev-server --host 0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes: *app

  streaming:
    restart: always
    build: *build
    image: mastodon-development
    env_file: .env
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    restart: always
    build: *build
    image: mastodon-development
    env_file: .env
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes: *app
