version: '3'
services:

  db:
    image: postgres:alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data

  web:
    build: &build
      context: .
      dockerfile: Dockerfile-development
    image: mastodon-development
    env_file: .env
    command: bundle exec foreman start -f Procfile.dev.docker
    ports:
      - "3001:3001"
      - "3035:3035"
    depends_on:
      - db
      - redis
    volumes: &app
      - ./.rspec:/mastodon/.rspec:cached
      - ./Procfile.dev.docker:/mastodon/Procfile.dev.docker:cached
      - ./.rubocop.yml:/mastodon/.rubocop.yml:cached
      - ./.ruby-version:/mastodon/.ruby-version:cached
      - ./.yardopts:/mastodon/.yardopts:cached
      - ./app:/mastodon/app:cached
      - ./bin:/mastodon/bin:cached
      - ./config:/mastodon/config:cached
      - ./config.ru:/mastodon/config.ru:cached
      - ./db:/mastodon/db:cached
      - ./docs:/mastodon/docs:cached
      - ./Gemfile:/mastodon/Gemfile:cached
      - ./Gemfile.lock:/mastodon/Gemfile.lock:cached
      - ./package.json:/mastodon/package.json:cached
      - ./yarn.lock:/mastodon/yarn.lock:cached
      - ./lib:/mastodon/lib:cached
      - ./public:/mastodon/public
      - ./public/packs:/mastodon/public/packs
      - ./spec:/mastodon/spec:cached
      - ./storybook:/mastodon/storybook:cached
      - ./streaming:/mastodon/streaming:cached
      - ./vendor/assets:/mastodon/vendor/assets
      - ./tmp/letter_opener:/mastodon/tmp/letter_opener

  streaming:
    build: *build
    image: mastodon-development
    env_file: .env
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: *build
    image: mastodon-development
    env_file: .env
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes: *app
